version: '3.8'
services:
  db:
    image: 'postgres:14'
    container_name: db
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - 'comaty-volumes:/var/lib/postgresql/data'
    networks:
      - comaty-networks

  serevr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres?schema=public
    networks:
      - comaty-networks
    volumes:
      - .:/app
      - /app/node_modules
      - ./schema.graphql:/app/schema.graphql
    ports:
      - 4000:4000
      - 5555:5555
    depends_on:
      - db

volumes:
  comaty-volumes:
networks:
  comaty-networks:
    driver: bridge
